apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-backend
spec:
  provider:
      gcpsm:                                                  
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcpsm-secret
              key: secret-access-credentials                           
        projectID: focal-plateau-372221
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-external-secret
spec:
  secretStoreRef:
    kind: SecretStore
    name: gcp-backend
  target:                                                             
    name: tikobot-secret 
  data:                                                       
  - secretKey: TOKEN
    remoteRef:            
      key: TOKEN
  - secretKey: mongoPath
    remoteRef:            
      key: mongoPath
  - secretKey: openAiKey
    remoteRef:            
      key: openAiKey
  - secretKey: alphaVantageKey
    remoteRef:            
      key: alphaVantageKey
  