name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
      PREFIX: ${{ secrets.PREFIX }}
      openAiKey: ${{ secrets.OPENAIKEY }}
      mongoPath: ${{ secrets.MONGOPATH }}
      alphaVantageKey: ${{ secrets.ALPHAVANTAGEKEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - uses: actions/checkout@v3
    - name: Build TikoBot production
      run: |
        ls -la
        docker build . --file Dockerfile --tag tikobot:latest
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push
